apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    name: hazelcast
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: mwrona/kubernetes-hazelcast:0.0.1
        imagePullPolicy: Always
        env:
          - name: "group.name"
            value: "k8s"
          - name: "group.password"
            value: "k8s"
          - name: "JAVA_OPTS"
            value: "-Xmx512m"
        ports:
        - name: hazelcast
          containerPort: 5701